<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Signals Migration
 *
 * Records all trade signals generated by the strategy, even if not executed.
 * This enables:
 * - Backtesting validation: Compare generated signals with historical data
 * - Strategy tuning: Why were signals skipped? (spread too high, session filter, etc.)
 * - ML training: Features JSON stores indicator values for future ML models
 *
 * WHY store non-executed signals?
 * - "If we had taken that signal, what would have happened?"
 * - Identify if filters are too strict (skipping profitable signals)
 * - Complete audit trail for strategy debugging
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('signals', function (Blueprint $table) {
            $table->id();

            // Which strategy generated this signal
            $table->foreignId('strategy_id')
                ->constrained()
                ->cascadeOnDelete();

            // Signal details
            $table->string('symbol', 20);
            $table->string('timeframe', 10);
            $table->enum('direction', ['buy', 'sell']);

            // Proposed trade levels at signal generation time
            $table->decimal('entry_price', 12, 5);
            $table->decimal('sl_price', 12, 5);
            $table->decimal('tp1_price', 12, 5);
            $table->decimal('tp2_price', 12, 5);
            $table->decimal('tp3_price', 12, 5);

            // Calculated lot size based on risk management rules
            $table->decimal('suggested_lot_size', 8, 4)->nullable();

            // Strategy confidence in this signal (0.0 to 1.0)
            // Future: Use for position sizing or filtering
            $table->decimal('confidence_score', 5, 4)->nullable();

            // =====================================================
            // FEATURES (for ML and analysis)
            // JSON object with indicator values at signal time
            // =====================================================
            // Example: {
            //   "ema_fast": 2345.67,
            //   "ema_slow": 2340.12,
            //   "adx": 28.5,
            //   "atr": 4.2,
            //   "rsi": 65.3,
            //   "spread_pips": 0.3
            // }
            $table->json('features')->nullable();

            // =====================================================
            // EXECUTION STATUS
            // =====================================================

            // Was this signal actually traded?
            $table->boolean('was_executed')->default(false);

            // If not executed, why?
            // Examples: "spread_too_high", "max_trades_reached", "news_filter", "session_closed"
            $table->string('skip_reason')->nullable();

            // Link to resulting trade (if executed)
            // nullOnDelete: if trade is deleted, signal remains for analysis
            $table->foreignId('resulting_trade_id')
                ->nullable()
                ->constrained('trades')
                ->nullOnDelete();

            // When the signal was generated by the strategy
            $table->timestamp('generated_at');

            $table->timestamps();

            // =====================================================
            // INDEXES
            // =====================================================

            // Find signals for a symbol in date range
            $table->index(['symbol', 'generated_at']);

            // Analyze execution rate
            $table->index('was_executed');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('signals');
    }
};
