<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Signal Model
 *
 * Records all trade signals generated by strategies, including those not executed.
 * This enables:
 * - Backtesting validation
 * - Strategy tuning (why were signals skipped?)
 * - ML training data (features JSON stores indicator values)
 */
class Signal extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'strategy_id',
        'symbol',
        'timeframe',
        'direction',
        'entry_price',
        'sl_price',
        'tp1_price',
        'tp2_price',
        'tp3_price',
        'suggested_lot_size',
        'confidence_score',
        'features',
        'was_executed',
        'skip_reason',
        'resulting_trade_id',
        'generated_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            // Prices - 5 decimal places for gold
            'entry_price' => 'decimal:5',
            'sl_price' => 'decimal:5',
            'tp1_price' => 'decimal:5',
            'tp2_price' => 'decimal:5',
            'tp3_price' => 'decimal:5',

            // Lot size - 4 decimal places
            'suggested_lot_size' => 'decimal:4',

            // Confidence score - 4 decimal places (0.0000 to 1.0000)
            'confidence_score' => 'decimal:4',

            // Features JSON - indicator values at signal time
            // Example: {"ema_fast": 2345.67, "adx": 28.5, "atr": 4.2}
            'features' => 'array',

            // Boolean
            'was_executed' => 'boolean',

            // Timestamp
            'generated_at' => 'datetime',
        ];
    }

    // =========================================================================
    // RELATIONSHIPS
    // =========================================================================

    /**
     * The strategy that generated this signal.
     */
    public function strategy(): BelongsTo
    {
        return $this->belongsTo(Strategy::class);
    }

    /**
     * The trade that resulted from this signal (if executed).
     * Null if signal was skipped.
     */
    public function resultingTrade(): BelongsTo
    {
        return $this->belongsTo(Trade::class, 'resulting_trade_id');
    }
}
