<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Strategy Model
 *
 * Defines trading strategy parameters. Each strategy is a complete set of rules:
 * - Entry signals (EMA crossover, ADX filter)
 * - Take profit levels (TP1, TP2, TP3 with partial close percentages)
 * - Stop loss calculation (ATR-based)
 * - Exit rules (reversal detection, max holding time)
 *
 * WHY configurable strategies?
 * - Optimize parameters without code changes
 * - A/B test different settings
 * - Run multiple strategies simultaneously (future)
 */
class Strategy extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_id',
        'name',
        'symbol',
        'timeframe_entry',
        'timeframe_trend',
        'ema_fast',
        'ema_slow',
        'adx_threshold',
        'atr_period',
        'tp1_pips',
        'tp1_close_pct',
        'tp2_pips',
        'tp2_close_pct',
        'tp3_pips',
        'tp3_close_pct',
        'sl_atr_multiplier',
        'exit_on_reversal',
        'max_holding_bars',
        'is_active',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            // Booleans
            'exit_on_reversal' => 'boolean',
            'is_active' => 'boolean',

            // Decimals for price/pip calculations
            'adx_threshold' => 'decimal:2',
            'tp1_pips' => 'decimal:2',
            'tp1_close_pct' => 'decimal:2',
            'tp2_pips' => 'decimal:2',
            'tp2_close_pct' => 'decimal:2',
            'tp3_pips' => 'decimal:2',
            'tp3_close_pct' => 'decimal:2',
            'sl_atr_multiplier' => 'decimal:2',
        ];
    }

    // =========================================================================
    // RELATIONSHIPS
    // =========================================================================

    /**
     * The user who owns this strategy.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * All trades generated by this strategy.
     */
    public function trades(): HasMany
    {
        return $this->hasMany(Trade::class);
    }

    /**
     * All signals generated by this strategy.
     * Includes both executed and skipped signals.
     */
    public function signals(): HasMany
    {
        return $this->hasMany(Signal::class);
    }
}
